const APP='https://w3bc-balancer.vercel.app';
const TOKENS=[
 {symbol:'SOL',mint:'So11111111111111111111111111111111111111112',lane:'CORE'},
 {symbol:'JUP',mint:'JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN',lane:'CORE'},
 {symbol:'JTO',mint:'jtojtomepa8beP8AuQc6eXt5FriJwfFMwY4Qm6rASfR',lane:'CORE'},
 {symbol:'BONK',mint:'DezXAZ8z7PnrnRJjz3wXBoRgixCa6fhXtKTq9vQ6WnC',lane:'HIGH_VOL'},
 {symbol:'WIF',mint:'EKpQGSJtjMFqKZ9KQanSqYXRcF8fBopzL4jM4FqkPZ5',lane:'HIGH_VOL'},
 {symbol:'JCHAINS',mint:'5qzX8fkFtVu7XbopVuHrCYFC2w1YsVAryN3WJeq1pump',lane:'MICROCAP'}
];
async function dex(t){const r=await fetch(`https://api.dexscreener.com/token-pairs/v1/solana/${t.mint}`,{headers:{accept:'application/json'}});if(!r.ok)throw new Error(`DexScreener ${r.status}`);const pairs=await r.json();if(!Array.isArray(pairs)||!pairs.length)throw new Error('No market pair');const p=pairs.sort((a,b)=>Number(b.liquidity?.usd||0)-Number(a.liquidity?.usd||0))[0];const m5=Math.abs(Number(p.priceChange?.m5||0)),h1=Math.abs(Number(p.priceChange?.h1||0)),v5=Number(p.volume?.m5||0),v1=Number(p.volume?.h1||0),liq=Number(p.liquidity?.usd||0),buys=Number(p.txns?.m5?.buys||0),sells=Number(p.txns?.m5?.sells||0),tx=buys+sells,velocity=Math.min(35,m5*6),range=Math.min(20,h1*1.5),volScore=Math.min(20,Math.log10(Math.max(1,v5))*3),liqScore=Math.min(15,Math.log10(Math.max(1,liq))*2),activity=Math.min(10,tx/3),score=Math.round(Math.min(100,velocity+range+volScore+liqScore+activity));return{...t,score,priceUsd:Number(p.priceUsd||0),m5,h1,v5,v1,liq,buys,sells,pairAddress:p.pairAddress,dexId:p.dexId,url:p.url}}
async function inspect(t){const usd=t.lane==='MICROCAP'?5:10;const r=await fetch(`${APP}/api/inspect?mint=${encodeURIComponent(t.mint)}&usd=${usd}`,{headers:{accept:'application/json'},cache:'no-store'});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||`inspect ${r.status}`);return d}
async function telegram(text,url){const token=process.env.TELEGRAM_BOT_TOKEN,chat=process.env.TELEGRAM_CHAT_ID;if(!token||!chat)return{sent:false,reason:'Telegram env not configured'};const body={chat_id:chat,text,disable_web_page_preview:true,reply_markup:{inline_keyboard:[[{text:'OPEN BALANCER',url}]]}};const r=await fetch(`https://api.telegram.org/bot${token}/sendMessage`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const d=await r.json();return{sent:Boolean(d.ok),result:d}}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');if(process.env.CRON_SECRET&&req.headers.authorization!==`Bearer ${process.env.CRON_SECRET}`&&req.query.key!==process.env.CRON_SECRET)return res.status(401).json({ok:false,error:'Unauthorized'});try{const rows=(await Promise.all(TOKENS.map(async t=>{try{return await dex(t)}catch(e){return{...t,score:0,error:e.message}}}))).sort((a,b)=>b.score-a.score);const candidates=rows.filter(x=>x.score>=55).slice(0,3);const checked=[];for(const c of candidates){try{const route=await inspect(c);checked.push({...c,route,qualified:route.eligible&&c.score>=65&&c.m5>=0.6&&c.liq>=10000})}catch(e){checked.push({...c,qualified:false,routeError:e.message})}}const best=checked.find(x=>x.qualified)||null;let alert={sent:false,reason:'No qualified opportunity'};if(best){const size=best.lane==='MICROCAP'?5:10;const text=`🔥 W3BC OPPORTUNITY\n${best.symbol} · SCORE ${best.score}/100\n5m move: ${best.m5.toFixed(2)}%\n1h move: ${best.h1.toFixed(2)}%\n5m volume: $${Math.round(best.v5).toLocaleString()}\nLiquidity: $${Math.round(best.liq).toLocaleString()}\nRound trip: ${Number(best.route.roundTripCostPct).toFixed(2)}%\nImpact: ${Number(best.route.maxImpactPct).toFixed(2)}%\nPilot size: ~$${size}\n\nReview in Balancer, then approve in Phantom.`;alert=await telegram(text,APP)}return res.status(200).json({ok:true,mode:'AUTOPILOT_APPROVAL',updatedAt:new Date().toISOString(),best,market:rows,checked,alert,executionEnabled:false})}catch(e){return res.status(502).json({ok:false,error:e.message||'Autopilot failed'})}}
