const SEEDS=[
 {symbol:'SOL',mint:'So11111111111111111111111111111111111111112',source:'seed'},
 {symbol:'JUP',mint:'JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN',source:'seed'},
 {symbol:'JTO',mint:'jtojtomepa8beP8AuQc6eXt5FriJwfFMwY4Qm6rASfR',source:'seed'},
 {symbol:'BONK',mint:'DezXAZ8z7PnrnRJjz3wXBoRgixCa6fhXtKTq9vQ6WnC',source:'seed'},
 {symbol:'WIF',mint:'EKpQGSJtjMFqKZ9KQanSqYXRcF8fBopzL4jM4FqkPZ5',source:'seed'},
 {symbol:'JCHAINS',mint:'5qzX8fkFtVu7XbopVuHrCYFC2w1YsVAryN3WJeq1pump',source:'seed'}
];
async function j(url){const r=await fetch(url,{headers:{accept:'application/json'}});if(!r.ok)throw new Error(`${new URL(url).hostname} ${r.status}`);return r.json()}
function uniq(list){const m=new Map();for(const x of list){if(!x?.mint)continue;if(!m.has(x.mint))m.set(x.mint,x)}return [...m.values()]}
async function promoted(){const out=[];for(const url of ['https://api.dexscreener.com/token-boosts/top/v1','https://api.dexscreener.com/token-profiles/latest/v1']){try{const rows=await j(url);for(const x of rows||[]){if(String(x.chainId).toLowerCase()!=='solana')continue;const mint=x.tokenAddress||x.address;if(mint)out.push({symbol:x.symbol||'DISCOVERED',mint,source:'dexscreener'})}}catch{}}return out}
async function bestPair(t){const pairs=await j(`https://api.dexscreener.com/token-pairs/v1/solana/${t.mint}`);if(!Array.isArray(pairs)||!pairs.length)throw new Error('No Solana pair');const p=pairs.sort((a,b)=>Number(b.liquidity?.usd||0)-Number(a.liquidity?.usd||0))[0];const liq=Number(p.liquidity?.usd||0),v5=Number(p.volume?.m5||0),v1=Number(p.volume?.h1||0),m5=Number(p.priceChange?.m5||0),h1=Number(p.priceChange?.h1||0),buys=Number(p.txns?.m5?.buys||0),sells=Number(p.txns?.m5?.sells||0),ageMin=p.pairCreatedAt?(Date.now()-Number(p.pairCreatedAt))/60000:null;const movement=Math.abs(m5),hourMove=Math.abs(h1),tx=buys+sells,velocity=Math.min(32,movement*7),hour=Math.min(18,hourMove*1.8),volume=Math.min(20,Math.log10(Math.max(1,v5))*3.4),liquidity=Math.min(18,Math.log10(Math.max(1,liq))*2.5),activity=Math.min(12,tx/2);let score=Math.round(Math.min(100,velocity+hour+volume+liquidity+activity));const tooNew=ageMin!=null&&ageMin<20,thin=liq<15000,dead=v5<1500&&movement<.5;if(tooNew)score-=25;if(thin)score-=25;if(dead)score-=20;return{symbol:p.baseToken?.symbol||t.symbol||'UNKNOWN',name:p.baseToken?.name||null,mint:t.mint,source:t.source,score:Math.max(0,score),priceUsd:Number(p.priceUsd||0),m5,h1,v5,v1,liq,buys,sells,ageMin,pairAddress:p.pairAddress,dexId:p.dexId,url:p.url,prequalified:!tooNew&&!thin&&!dead&&score>=50,rejectReason:tooNew?'TOO_NEW':thin?'LOW_LIQUIDITY':dead?'DEAD_MONEY':null}}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');try{const candidates=uniq([...SEEDS,...await promoted()]).slice(0,60);const rows=[];for(let i=0;i<candidates.length;i+=8){const batch=await Promise.all(candidates.slice(i,i+8).map(async t=>{try{return await bestPair(t)}catch(e){return{symbol:t.symbol,mint:t.mint,source:t.source,score:0,prequalified:false,error:e.message}}}));rows.push(...batch)}rows.sort((a,b)=>(b.score||0)-(a.score||0));return res.status(200).json({ok:true,updatedAt:new Date().toISOString(),scanned:candidates.length,prequalified:rows.filter(x=>x.prequalified).length,opportunities:rows.slice(0,30)})}catch(e){return res.status(502).json({ok:false,error:e.message||'Discovery failed'})}}
