const USDC='EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v';
const UNIVERSE=[
 {symbol:'SOL',mint:'So11111111111111111111111111111111111111112',decimals:9,lane:'CORE'},
 {symbol:'JUP',mint:'JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN',decimals:6,lane:'CORE'},
 {symbol:'JTO',mint:'jtojtomepa8beP8AuQc6eXt5FriJwfFMwY4Qm6rASfR',decimals:9,lane:'CORE'},
 {symbol:'BONK',mint:'DezXAZ8z7PnrnRJjz3wXBoRgixCa6fhXtKTq9vQ6WnC',decimals:5,lane:'HIGH_VOL'},
 {symbol:'WIF',mint:'EKpQGSJtjMFqKZ9KQanSqYXRcF8fBopzL4jM4FqkPZ5',decimals:6,lane:'HIGH_VOL'},
 {symbol:'JCHAINS',mint:'5qzX8fkFtVu7XbopVuHrCYFC2w1YsVAryN3WJeq1pump',decimals:6,lane:'MICROCAP'}
];
async function rawQuote(inputMint,outputMint,amount){const u=new URL('https://lite-api.jup.ag/swap/v1/quote');u.searchParams.set('inputMint',inputMint);u.searchParams.set('outputMint',outputMint);u.searchParams.set('amount',String(amount));u.searchParams.set('slippageBps','100');u.searchParams.set('restrictIntermediateTokens','true');const r=await fetch(u,{headers:{accept:'application/json'}});if(!r.ok)throw new Error(`quote ${r.status}`);const q=await r.json();if(!q.outAmount)throw new Error(q.error||'no route');return q}
async function inspect(t,usd=10){const buy=await rawQuote(USDC,t.mint,Math.floor(usd*1e6));const tokenRaw=Number(buy.outAmount),tokenOut=tokenRaw/10**t.decimals;if(!tokenOut)throw new Error('zero output');const sell=await rawQuote(t.mint,USDC,Math.floor(tokenRaw));const roundTripUsd=Number(sell.outAmount)/1e6,roundTripCostPct=Math.max(0,(1-roundTripUsd/usd)*100),buyImpactPct=Math.abs(Number(buy.priceImpactPct||0)),sellImpactPct=Math.abs(Number(sell.priceImpactPct||0)),maxImpactPct=Math.max(buyImpactPct,sellImpactPct);return{priceUsd:usd/tokenOut,buyImpactPct,sellImpactPct,maxImpactPct,roundTripUsd,roundTripCostPct,routeSafe:maxImpactPct<=1&&roundTripCostPct<=2}}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');try{const rows=await Promise.all(UNIVERSE.map(async t=>{try{const q=await inspect(t,t.lane==='MICROCAP'?5:10);return{...t,...q,tradable:true,eligible:q.routeSafe}}catch(e){return{...t,tradable:false,eligible:false,error:e.message}}}));rows.sort((a,b)=>(Number(b.eligible)-Number(a.eligible))||(a.roundTripCostPct??999)-(b.roundTripCostPct??999));return res.status(200).json({ok:true,updatedAt:new Date().toISOString(),universe:rows,policy:{homeBase:'USDC',maxOpenPositions:2,maxPositionUsd:25,microcapMaxPositionUsd:10,maxRouteImpactPct:1,maxRoundTripCostPct:2,executionEnabled:false}})}catch(e){return res.status(502).json({ok:false,error:e.message})}}
